import { useState } from 'react'

export function GroupProposals({ proposals, results, createProposal, vote, removeVote, finalize, close, updateProposal, canManage }) {
	const [type, setType] = useState('other')
	const [form, setForm] = useState({ title: '', destination: '', name: '', day_number: '1', meal_index: '0', activity_index: '0', item_index: '0', value: '' })
	const updateForm = event => setForm({ ...form, [event.target.name]: event.target.value })
	const submit = event => { event.preventDefault(); const payload = { value: form.value }; if (type === 'destination') payload.destination = form.destination; if (['hotel', 'restaurant', 'activity', 'itinerary_item'].includes(type)) payload.day_number = Number(form.day_number); if (type === 'restaurant') payload.meal_index = Number(form.meal_index); if (type === 'activity') payload.activity_index = Number(form.activity_index); if (type === 'itinerary_item') payload.item_index = Number(form.item_index); if (['hotel', 'restaurant', 'activity'].includes(type)) payload.name = form.name; createProposal({ proposal_type: type, title: form.title, payload }); setForm({ ...form, title: '', value: '' }) }
	return <section className="panel"><h2>Proposals</h2>{proposals.length === 0 && <p>No proposals yet.</p>}{proposals.map(proposal => { const result = results[proposal.id]; const tied = result?.ties?.length > 1; return <article key={proposal.id}><h3>{proposal.title}</h3><p>{proposal.description || 'Open for votes'} · {proposal.status}{proposal.deadline && ` · closes ${new Date(proposal.deadline).toLocaleString()}`}</p>{result && <p>Results: {Object.entries(result.counts).map(([choice, count]) => `${choice}: ${count}`).join(', ') || 'No votes'}{tied ? ` · tie: ${result.ties.join(', ')}` : result.winner ? ` · winner: ${result.winner}` : ''} · your vote: {result.user_vote || 'none'}</p>}{proposal.status === 'open' && <><input aria-label={`Vote for ${proposal.title}`} placeholder="Your choice" onKeyDown={event => { if (event.key === 'Enter' && event.currentTarget.value.trim()) { vote(proposal.id, event.currentTarget.value.trim()); event.currentTarget.value = '' } }} /><button className="button button-quiet" onClick={() => removeVote(proposal.id)}>Remove my vote</button></>}{canManage && proposal.status === 'open' && <><button className="button button-quiet" onClick={() => close(proposal.id)}>Close</button><button className="button button-quiet" onClick={() => updateProposal(proposal)}>Edit</button><button className="button button-primary" onClick={() => finalize(proposal.id)}>Finalize</button></>}</article>})}<form onSubmit={submit}><select value={type} onChange={event => setType(event.target.value)}><option value="destination">Destination</option><option value="hotel">Hotel</option><option value="restaurant">Restaurant</option><option value="activity">Activity</option><option value="itinerary_item">Itinerary item</option><option value="other">Other</option></select><input name="title" value={form.title} onChange={updateForm} placeholder="Proposal title" required />{type === 'destination' && <input name="destination" value={form.destination} onChange={updateForm} placeholder="Destination" required />}{type !== 'destination' && type !== 'other' && <><input name="name" value={form.name} onChange={updateForm} placeholder="Name" /><input name="day_number" type="number" min="1" value={form.day_number} onChange={updateForm} />{type === 'restaurant' && <input name="meal_index" type="number" min="0" value={form.meal_index} onChange={updateForm} />}{type === 'activity' && <input name="activity_index" type="number" min="0" value={form.activity_index} onChange={updateForm} />}{type === 'itinerary_item' && <input name="item_index" type="number" min="0" value={form.item_index} onChange={updateForm} />}</>}<textarea name="value" value={form.value} onChange={updateForm} placeholder="Proposed details" required /><button className="button button-primary" type="submit">Create proposal</button></form></section>
}
