from alembic import op
import sqlalchemy as sa
revision = "20260913_000009"
down_revision = "20260913_000008"
branch_labels = depends_on = None
def upgrade():
    op.create_table("proposals", sa.Column("id", sa.String(36), primary_key=True), sa.Column("trip_id", sa.String(36), sa.ForeignKey("trips.id", ondelete="CASCADE"), nullable=False), sa.Column("created_by_user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("proposal_type", sa.String(30), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text), sa.Column("payload", sa.JSON, nullable=False), sa.Column("status", sa.String(20), nullable=False), sa.Column("deadline", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("closed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("proposal_type IN ('destination', 'hotel', 'restaurant', 'activity', 'itinerary_item', 'other')", name="ck_proposal_type"), sa.CheckConstraint("status IN ('draft', 'open', 'closed', 'accepted', 'rejected', 'cancelled')", name="ck_proposal_status"))
    op.create_table("proposal_votes", sa.Column("id", sa.String(36), primary_key=True), sa.Column("proposal_id", sa.String(36), sa.ForeignKey("proposals.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id"), nullable=False), sa.Column("choice_key", sa.String(120), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("proposal_id", "user_id", name="uq_proposal_vote_user"))
def downgrade(): op.drop_table("proposal_votes"); op.drop_table("proposals")
