import { useAuth } from '../auth/useAuth'
import { Link } from 'react-router-dom'

export default function ProfilePage() {
  const { user, logout } = useAuth()
  return <section className="profile-page page-container"><div className="profile-heading"><p className="eyebrow">Your travel identity</p><h1>Profile</h1><p>Keep the details that make every plan feel more like yours.</p></div><div className="profile-layout"><div className="profile-card profile-intro-card"><div className="profile-avatar">{(user?.name || 'P').slice(0, 1).toUpperCase()}</div><h2>{user?.name || 'Traveler'}</h2><p>{user?.email || 'Your email address'}</p><button className="text-button">Change photo</button></div><div className="profile-card"><SectionTitle title="Travel preferences" /><div className="preference-grid"><Preference label="Travel style" value="Not set yet" /><Preference label="Budget preference" value="Flexible" /><Preference label="Favorite destinations" value="Add destinations" /><Preference label="Interests" value="Food, culture, nature" /></div></div><div className="profile-card profile-account"><SectionTitle title="Account" /><div className="account-row"><div><strong>Security</strong><p>Password and sign-in settings</p></div><span>Coming soon</span></div><div className="account-row"><div><strong>Notifications</strong><p>Trip updates and planning reminders</p></div><span>Coming soon</span></div><button className="logout-button" onClick={logout}>Log out</button></div></div><div className="profile-next"><span>Ready for another idea?</span><Link to="/plan">Plan a new trip ↗</Link></div></section>
}

function SectionTitle({ title }) { return <div className="section-title-row"><h2>{title}</h2><button className="text-button">Edit</button></div> }
function Preference({ label, value }) { return <div className="preference-item"><span>{label}</span><strong>{value}</strong></div> }